Add proxyUrls column to UserSettings model
movie-web/backend pull request #28
Opened 2023-12-29 22:00 UTC by qtchaos

This pull request resolves [#539](https://github.com/movie-web/movie-web/issues/539)

Adds the proxyUrls column to the UserSettings model, allowing users to sync proxies between devices.

 - [X] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [X] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [X] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [X] I have tested all of my changes.

2023-12-30 21:37 UTC, binaryoverload approved these changes

2024-01-01 17:04 UTC, mrjvs requested changes
Looks good, only one small change

2024-01-01 17:04 UTC, mrjvs commented on src/db/models/UserSettings.ts
> +  @Property({ name: 'proxy_urls', nullable: true, type: 'text[]' })
I prefer a more typesafe declaration of using arrays. You can use `ArrayType` https://mikro-orm.io/docs/custom-types#arraytype

2024-01-01 17:04 UTC, mrjvs commented on src/db/models/UserSettings.ts
> +  @Property({ name: 'proxy_urls', nullable: true, type: 'text[]' })
Should work exactly the same as how you specified it before.

2024-01-01 18:03 UTC, mrjvs approved these changes

2024-01-01 18:04 UTC, merged