- Fixed default boolean value for zod
movie-web/backend pull request #33
Opened 2024-01-05 06:13 UTC by spewmaker

This pull request resolves Issue 586 (https://github.com/movie-web/movie-web/issues/586)

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2024-01-05 09:13 UTC, binaryoverload commented
Have you tested this? I'm not sure this will resolve the issue.

I believe this needs to be a call to `.enum` to check it's either "true" or "false" and `.transform` to do `value == "true"`

It's the `.coerce` that's causing the problem

2024-01-05 16:44 UTC, spewmaker commented
@binaryoverload I see, I thought it was the `.default()` causing the issue, I will take a look and update PR

2024-01-05 16:52 UTC, binaryoverload commented
> @binaryoverload I see, I thought it was the `.default()` causing the issue, I will take a look and update PR

Great, thanks!

2024-01-05 18:48 UTC, spewmaker commented
@binaryoverload I used zod enum to fix the boolean values however I kept unrelated getting zod errors on postgres, crypto, and meta objects.
I made changes to fix that, I am not sure what was causing those zod errors.
`ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "postgres"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "crypto"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "meta"
    ],
    "message": "Required"
  }
]`

2024-01-05 18:53 UTC, mrjvs commented
@spewmaker make sure you have your local configured correctly. See the configuration requirements here: https://docs.movie-web.app/backend/configuration

2024-01-05 18:54 UTC, spewmaker commented
@mrjvs ah okay, I can not open the link you provided right now, my work wifi blocks it, I will take a look when I am back home.

2024-01-05 22:05 UTC, binaryoverload requested changes

2024-01-05 22:05 UTC, binaryoverload commented on src/config/schema.ts
> +    }),
Instead of doing this for everything, we can do `defaultBoolean.default("false")` and maybe rename `defaultBoolean` to `booleanSchema`

```suggestion
    .default({
      enabled: 'false',
    }),
```

2024-01-07 17:56 UTC, mrjvs requested changes

2024-01-07 17:56 UTC, mrjvs commented on src/config/orm.ts
> +  .transform((val) => val === 'true');
If we do a `z.preprocess()`. We can use it as a normal zod boolean. we can then use `.default(false)` without any strings. Then there would be no need to change any defaults either.

2024-01-24 16:25 UTC, gsi-kevincarrera commented
I think will be a great idea to make something like this:
```bash
export const booleanSchema = z
  .enum(['true', 'false'])
  .catch('false')
  .transform((value) => value == 'true');
```

2024-01-24 16:36 UTC, mrjvs commented
Preprocess is better, since it's actually treated as a boolean in every step of the way after processing. See my review comment

2024-01-24 17:09 UTC, gsi-kevincarrera commented
Something like this?
```javascript
const booleanSchema = z.preprocess(
  (val) => val === 'true',
  z.boolean()
).default(false)

```

2024-01-24 17:13 UTC, mrjvs commented
yea, but without the default. Default should be handled by the config schema itself. not by the boolean

2024-01-24 17:29 UTC, gsi-kevincarrera commented
Should I make a pr or just wait for @spewmaker to see this?

2024-01-24 17:31 UTC, mrjvs commented
Go for it, I dont think spewmaker is going to finish it

2024-01-24 17:45 UTC, closed without merging

2024-01-24 17:45 UTC, mrjvs commented
Superseeded by #37